### PR TITLE
Update to v3 endpoint

### PR DESCRIPTION
**Pull request by msft-tsharp**
This updates the API endpoints to the default v3.0. This is fully compatible with the v2.0 endpoints including schema.

### CODE REVIEW

**Comment by p0w3rsh3ll** [comment]
@msft-tsharp Thanks for letting me know. Yes, I'll have a look at this change.
Another question, can we get rid of the deprecated ADAL library and the API key in the code?

**Comment by vishnu4** [comment]
I've added a work item for our team to make that requested change, we'll plan on including that in another separate PR.  Was this current one able to work for yoU?

**Comment by p0w3rsh3ll** [comment]
> I've added a work item for our team to make that requested change, we'll plan on including that in another separate PR. Was this current one able to work for you?

@vishnu4, ok to do it in a separate PR. Yes, v3.0 works for me after several changes in the code. I plan to add changes back to this repo before the end of 2023.

**Comment by p0w3rsh3ll** [comment]
I think it's complete. I'll make a PR from my own repo with the above changes.
It can be tested and when it's ok, the version in the psd1 file can be increased...

**Comment by p0w3rsh3ll** [comment]
PR done: see #126

**Pull request closed without merging**
