### PR TITLE
Update to v3

### PR DESCRIPTION
**Pull request by p0w3rsh3ll**
Related to #125

### CODE REVIEW

**Comment by vishnu4** [comment]
hello there @p0w3rsh3ll .  Looking over your PR it's clear that we made some output changes that were not intentional when migrating to .net core.  I've updated the output again, and hopefully some of your switch/cases won't be necessary any longer.  Could you please try again with your setup?  Thank you for your assistance!

**Comment by p0w3rsh3ll** [comment]
Hi @vishnu4,
I've tested the v3, I don't see changes. I've tested for example the threats types (severity and impact) using the json document. In v2, there are still as [long] (3 for severity and 0 for impact). In v3, there are still as [string]. Currently the switches/cases in the PR are still required. Can you please check your recent changes? There's maybe another issue.

The tests I did for example are:
```powershell
Set-MSRCApiKey -APIVersion 3.0
$cvrfDoc = Get-MsrcCvrfDocument -ID 2023-Nov
($cvrfDoc.vulnerability | Select -First 1).threats | gm
# type          NoteProperty string type=Impact
Set-MSRCApiKey -APIVersion 2.0
$cvrfDoc = Get-MsrcCvrfDocument -ID 2023-Nov
($cvrfDoc.vulnerability | Select -First 1).threats | gm
# Type          NoteProperty long Type=0
```

**Comment by vishnu4** [comment]
I did not notice the .Value change you had to make as well.  We're going to see if we can add that back in to avoid any breaking changes.  Will reach back when that's done.

**Comment by vishparekh** [comment]
Hi @p0w3rsh3ll - We’ve updated the v3.0 endpoint to align its output with v2.0. Could you please update the pull request accordingly? Thank you for you contribution!

**Comment by p0w3rsh3ll** [comment]
Hi @vishparekh,
I fixed the function so that it works both for v2.0 and v3.0 as they are aligned :-)

**Review by vishparekh — APPROVED** [review]

**Pull request merged**
