### PR TITLE
Adding CWE info 

### PR DESCRIPTION
**Pull request by p0w3rsh3ll**
Same reason as issue  #137 

> Following this [blog post from the MSRC about greater transparency](https://msrc.microsoft.com/blog/2024/04/toward-greater-transparency-adopting-the-cwe-standard-for-microsoft-cves/) and the adoption of CWE standard, it's possible to add this info to various functions in this module.

### CODE REVIEW

**Comment by p0w3rsh3ll** [comment]
Hello @vishparekh,
Can you please review this PR? 
Thanks
Best regards

**Review by LLotme — APPROVED** [review]
👍

**Comment by StanislavUhimenko** [comment]
Правильно

**Review by NameNoQuality — APPROVED** [review]
#NNQ

**Review by ninjafit — APPROVED** [review]

**Pull request merged**
